#!/bin/bash
# Workaround for "Bad owner or permissions on ~/.ssh/config"
# /home is a CIFS mount on the host, and files/directories in CIFS mounts
# have unchangeable owners and permissions set at the time of the mount.
# The configured owner and permissions are such that ssh's 'tamper-detection'
# verification of the Kudu user's /.ssh/config file fail.

# SSH gets user's home dir from /etc/passwd, not $HOME
config=$(getent passwd $(id -u) | cut -d: -f6)/.ssh/config

# If the config exists and -F was not already specified,
# skip the extended check by using -F to
# explicitly specify the file.
fileSpecified=false

for i in "$@" ; do
  if [[ $i == "-F" ]] ; then
    fileSpecified=true
    break
  fi
done

if [ -f $config ] && [ "$fileSpecified" = false ]; then
  ssh.original -F $config "$@"
else
  ssh.original "$@"
fi
